
### Get all users
GET http://localhost:3000/users/getusers

### Login user
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "user1"
}

### Add new user
POST http://localhost:3000/users/adduser
Content-Type: application/json

{
    "name": "user1",
  "age": 25,
  "email": "user1@gmail.com",
  "password": "user1",
  "phone": "1234567890",
  "country": "India",
  "role": "user"
}

### Update user
PUT http://localhost:3000/users/edituser/1
Content-Type: application/json

{
  "age": 26,
  "email": "user2@gmail.com",
  "phone": "1212121212",
  "country": "China"
}

### Get user by Id
GET http://localhost:3000/users/getuser/6

### Delete user
DELETE http://localhost:3000/users/deleteuser/16

### Add new user
POST http://localhost:3000/users/adduser
Content-Type: application/json

{
  "name": "admin11",
  "age": 25,
  "email": "admin1@gmail.com",
  "password": "admin11",
  "phone": "1234567890",
  "country": "India",
  "role": "admin"
}


### fetch user by role
GET http://localhost:3000/users/filter?role=user
Content-Type: application/json

### Fetch users by role 'admin'
GET http://localhost:3000/users/filter?role=admin
Content-Type:  application/json

###
GET http://localhost:3000/users/getpic
Accept: application/json

### Add User with Profile Picture
POST http://localhost:3000/users/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

sharvary
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="age"

24
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

sharvary@example.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

sharvary
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="phone"

1234567890
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="country"

India
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="role"

user
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="profile_pic"; filename="profile_pic.jpg"
Content-Type: image/jpeg

@C:/Users\skhandal\Downloads\Snehal Khandale_Photo.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


